# Student Loan Risk with Deep Learning

In [1]:
# Imports
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from pathlib import Path
import numpy as np 

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `student-loans.csv` file into a Pandas DataFrame. Review the DataFrame, looking for columns that could eventually define your features and target variables.   

In [2]:
# Read the csv into a Pandas DataFrame
file_path = "https://static.bc-edx.com/ai/ail-v-1-0/m18/lms/datasets/student-loans.csv"
loans_df = pd.read_csv(file_path)

# Review the DataFrame
loans_df.head()

payment_history  location_parameter  stem_degree_score  gpa_ranking  \
0              7.4                0.70               0.00          1.9   
1              7.8                0.88               0.00          2.6   
2              7.8                0.76               0.04          2.3   
3             11.2                0.28               0.56          1.9   
4              7.4                0.70               0.00          1.9   

   alumni_success  study_major_code  time_to_completion  \
0           0.076              11.0                34.0   
1           0.098              25.0                67.0   
2           0.092              15.0                54.0   
3           0.075              17.0                60.0   
4           0.076              11.0                34.0   

   finance_workshop_score  cohort_ranking  total_loan_score  \
0                  0.9978            3.51              0.56   
1                  0.9968            3.20              0.68   
2                  0.9970            3.26              0.65   
3                  0.9980            3.16              0.58   
4                  0.9978            3.51              0.56   

   financial_aid_score  credit_ranking  
0                  9.4               0  
1                  9.8               0  
2                  9.8               0  
3                  9.8               1  
4                  9.4               0

In [3]:
# Review the data types associated with the columns
loans_df.dtypes

payment_history           float64
location_parameter        float64
stem_degree_score         float64
gpa_ranking               float64
alumni_success            float64
study_major_code          float64
time_to_completion        float64
finance_workshop_score    float64
cohort_ranking            float64
total_loan_score          float64
financial_aid_score       float64
credit_ranking              int64
dtype: object

In [4]:
# Check the credit_ranking value counts
loans_df["credit_ranking"].value_counts()

credit_ranking
1    855
0    744
Name: count, dtype: int64

### Step 2: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “credit_ranking”. The remaining columns should define the features dataset.

In [5]:
# Define the target set y using the credit_ranking column
y = loans_df["credit_ranking"]

# Display a sample of y
display(y.head())


0    0
1    0
2    0
3    1
4    0
Name: credit_ranking, dtype: int64

In [6]:
# Define features set X by selecting all columns but credit_ranking
X = loans_df.drop(columns="credit_ranking")

# Review the features DataFrame
display(X.head())


payment_history  location_parameter  stem_degree_score  gpa_ranking  \
0              7.4                0.70               0.00          1.9   
1              7.8                0.88               0.00          2.6   
2              7.8                0.76               0.04          2.3   
3             11.2                0.28               0.56          1.9   
4              7.4                0.70               0.00          1.9   

   alumni_success  study_major_code  time_to_completion  \
0           0.076              11.0                34.0   
1           0.098              25.0                67.0   
2           0.092              15.0                54.0   
3           0.075              17.0                60.0   
4           0.076              11.0                34.0   

   finance_workshop_score  cohort_ranking  total_loan_score  \
0                  0.9978            3.51              0.56   
1                  0.9968            3.20              0.68   
2                  0.9970            3.26              0.65   
3                  0.9980            3.16              0.58   
4                  0.9978            3.51              0.56   

   financial_aid_score  
0                  9.4  
1                  9.8  
2                  9.8  
3                  9.8  
4                  9.4

### Step 3: Split the features and target sets into training and testing datasets.


In [7]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

### Step 4: Use scikit-learn's `StandardScaler` to scale the features data.

In [8]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_train_scaled = scaler.fit_transform(X_train)

# Transform the features testing dataset
X_test_scaled = scaler.transform(X_test)


---

## Compile and Evaluate a Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.


In [9]:
# Define the number of inputs (features) to the model
number_input_features = len(X.columns)

# Review the number of features
print("Number of input features:", number_input_features)


Number of input features: 11


In [10]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 = 80

# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 = 30

# Define the number of neurons in the output layer
number_output_neurons = 3

# Print the defined values
print("Number of nodes in the first hidden layer:", hidden_nodes_layer1)
print("Number of nodes in the second hidden layer:", hidden_nodes_layer2)
print("Number of neurons in the output layer:", number_output_neurons)

# Explain the output layer
print("\nExplanation of output layer:")
print(f"The output layer has {number_output_neurons} neurons because:")
print(loans_df["credit_ranking"].value_counts().sort_index())


Number of nodes in the first hidden layer: 80
Number of nodes in the second hidden layer: 30
Number of neurons in the output layer: 3

Explanation of output layer:
The output layer has 3 neurons because:
credit_ranking
0    744
1    855
Name: count, dtype: int64


In [11]:
# Create the Sequential model instance
nn = Sequential()

# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=number_output_neurons, activation="softmax"))

c:\Users\spenc\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [12]:
# Display the Sequential model summary
# Display the model summary
nn.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 80)             │           960 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 30)             │         2,430 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            93 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,483 (13.61 KB)

 Trainable params: 3,483 (13.61 KB)

 Non-trainable params: 0 (0.00 B)

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.


In [13]:
# Compile the Sequential model
nn.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# Print confirmation
print("Model compiled successfully with the following configuration:")
print(f"Optimizer: Adam")
print(f"Loss function: Sparse Categorical Crossentropy")
print(f"Metrics: Accuracy")


Model compiled successfully with the following configuration:
Optimizer: Adam
Loss function: Sparse Categorical Crossentropy
Metrics: Accuracy


In [14]:
# Fit the model using 50 epochs and the training data
model = nn.fit(
    X_train_scaled,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)    

Epoch 1/50
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.4902 - loss: 1.0139 - val_accuracy: 0.7383 - val_loss: 0.6851
Epoch 2/50
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6925 - loss: 0.6753 - val_accuracy: 0.7930 - val_loss: 0.5194
Epoch 3/50
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7454 - loss: 0.5587 - val_accuracy: 0.8008 - val_loss: 0.4702
Epoch 4/50
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7507 - loss: 0.5501 - val_accuracy: 0.8164 - val_loss: 0.4569
Epoch 5/50
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7843 - loss: 0.5001 - val_accuracy: 0.8047 - val_loss: 0.4526
Epoch 6/50
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7514 - loss: 0.5037 - val_accuracy: 0.8164 - val_loss: 0.4438
Epoch 7/50
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7715 - loss: 0.4836 - val_accuracy: 0.8086 - val_loss: 0.4415
Epoch 8/50
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7549 - loss: 0.5200 - val_accuracy: 0.8086 - val_loss:

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.


In [15]:
# Evaluate the model using the test data
loss, accuracy = nn.evaluate(X_test_scaled, y_test, verbose=1)

# Print the loss and accuracy
print(f"\nTest Loss: {loss}")
print(f"Test Accuracy: {accuracy}")


10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7935 - loss: 0.4783 

Test Loss: 0.4889664053916931
Test Accuracy: 0.78125


### Step 4: Save and export your model to a keras file, and name the file `student_loans.keras`.

In [16]:
# Set the model's file path
model_filepath = "student_loans.keras"

# Export your model to a keras file
nn.save(model_filepath)

# Print confirmation message
print(f"\nModel saved as {model_filepath}")



Model saved as student_loans.keras


---
## Predict Loan Repayment Success by Using your Neural Network Model

### Step 1: Reload your saved model.

In [17]:
from tensorflow.keras.models import load_model

# Load the model to a new object
new_model = load_model(model_filepath)

# Print confirmation message
print(f"\nModel loaded from {model_filepath}")



Model loaded from student_loans.keras


### Step 2: Make predictions on the testing data and save the predictions to a DataFrame.

In [18]:
# Make predictions with the test data
predictions = nn.predict(X_test_scaled)

# Display a sample of the predictions
sample_predictions = predictions[:5]  # Display the first 5 predictions
print("\nSample Predictions:")
print(sample_predictions)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 

Sample Predictions:
[[7.0697516e-01 2.9138577e-01 1.6391202e-03]
 [8.4210974e-01 1.5779078e-01 9.9489982e-05]
 [8.2608826e-02 9.1735971e-01 3.1422231e-05]
 [7.8027284e-01 2.1949759e-01 2.2959817e-04]
 [1.8753645e-01 8.1227291e-01 1.9061918e-04]]


In [19]:
# Check the shape of the predictions
print(f"\nShape of predictions: {predictions.shape}")

# If predictions are multi-dimensional, handle accordingly
if predictions.shape[1] > 1:
    # For multi-class or multi-output predictions
    binary_predictions = (predictions > 0.5).astype(int)
    predictions_df = pd.DataFrame(binary_predictions, columns=[f'Prediction_{i+1}' for i in range(predictions.shape[1])])
else:
    # For binary classification
    binary_predictions = (predictions > 0.5).astype(int)
    predictions_df = pd.DataFrame(binary_predictions, columns=['Prediction'])

# Display the DataFrame
print("\nPredictions DataFrame:")
print(predictions_df.head())


Shape of predictions: (320, 3)

Predictions DataFrame:
   Prediction_1  Prediction_2  Prediction_3
0             1             0             0
1             1             0             0
2             0             1             0
3             1             0             0
4             0             1             0


### Step 4: Display a classification report with the y test data and predictions

In [20]:
# Convert predictions to class labels based on your conditions
if predictions.shape[1] > 1:
    # For multi-class predictions
    y_pred_classes = np.argmax(predictions, axis=1)  # Get the predicted class labels
else:
    # For binary classification
    y_pred_classes = (predictions > 0.5).astype(int).flatten()  # Convert to binary class labels

# Print the classification report with the y test data and predictions
print("\nClassification Report:")
print(classification_report(y_test, y_pred_classes))


Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.79      0.76       141
           1       0.82      0.78      0.80       179

    accuracy                           0.78       320
   macro avg       0.78      0.78      0.78       320
weighted avg       0.78      0.78      0.78       320



---
## Discuss creating a recommendation system for student loans

Briefly answer the following questions in the space provided:

1. Describe the data that you would need to collect to build a recommendation system to recommend student loan options for students. Explain why this data would be relevant and appropriate.

2. Based on the data you chose to use in this recommendation system, would your model be using collaborative filtering, content-based filtering, or context-based filtering? Justify why the data you selected would be suitable for your choice of filtering method.

3. Describe two real-world challenges that you would take into consideration while building a recommendation system for student loans. Explain why these challenges would be of concern for a student loan recommendation system.

##Answers 

1. What student loans are the lowest risk (by school type)

2. context and content I believe, as there would be both context (loans) and content (marketing the loan)

3. Loan repayment, we always want lower risk. Breach of Data, would not want personal financial info out for the public to grab 